#!/usr/bin/env python2
# author : djunekz
# -*- coding: utf-8 -*-

from marshal import *
import os, sys, time
import fileinput

#color variable
N = '\033[0m'
D = '\033[90m'
W = '\033[1;37m'
B = '\033[1;34m'
R = '\033[1;31m'
G = '\033[1;32m'
Y = '\033[1;33m'
C = '\033[1;36m'
ask= G + '[' + W + 'Name File' + G + ']'
dwn= G + '[' + Y + '+' + G + ']'
up = G + '[' + R + '-' + G + ']'
tl= Y + '[' + W + 'Translate' + Y + ']'
sukses= G + '[' + W + '!' + G + ']'
eror= R + '[' + W + '!' + R + ']'

note= """ {}# NOTE{}""".format(R,W)
recode = """{}Jika ingin recode, jangan lupa cantumkan nama Author di tools kalian.
semudah itu untuk bersedekah.
""".format(Y)
version="""{}1.2.2{}""".format(G,N)
os.system("clear")
logo ="""

\t\33[1;31m     ____             _____ _____ ____   
\t\33[1;31m    | __ )  __ _\33[1;33m__  _\33[1;31m|_   _| ____|  _ \  
\t\33[1;31m    |  _ \ / _` \ \33[1;33m\/ /\33[1;31m | | |  _| | |_) | \33[0m
\t\33[1;37m    | |_) | (_| |\33[1;33m>  < \33[1;37m | | | |___|  _ <  
\t\33[1;37m    |____/ \__,_/\33[1;33m_/\_\ \33[1;37m|_| |_____|_| \_\ \33[0m

   \t\t \33[1;34m Author\33[1;36m :\33[1;33m D J U N E K Z
""".format(version)
print logo
inf = """
        \33[1;31m [\33[1;36m Simple Tools for Encrypt and Decrypt files\33[1;31m ]
"""
print inf
banner2 = """
        {}[{}1{}]{} Encrypt     {}[{}2{}]{} Decrypt     {}[{}3{}]{} Contact Me
        {}[{}x{}]{} Exit
""".format(G,Y,G,W,G,Y,G,W,G,Y,G,W,G,R,G,Y)

print banner2
cos = """
    {}[{}1{}]{} Termux
    {}[{}2{}]{} Linux
""".format(G,Y,G,W,G,Y,G,W)
def main(s):
      for c in s + "\n":
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(0.050)

def dekrip():
    try:
       sc = raw_input(ask + W + "Script " + G + "> " + W)
       f = open(sc,'r')
       filedata = f.read()
       f.close()

       newdata = filedata.replace("eval","echo")

       out = raw_input(ask + W + "Output" + G + "> " + W)
       f = open(out,'w')
       f.write(newdata)
       f.close()

       os.system("touch tes.sh")
       os.system("bash " + out + " > tes.sh")
       os.remove(out)
       os.system("mv -f tes.sh " + out)
       main (sukses + "Decrypt Successful...")
    except KeyboardInterrupt:
       print (eror + " Stopped!")
    except IOError:
       print (eror + " File Not Found!")
       os.system("sleep 3")
       dekrip()

def enkrip():
    try:
       script = raw_input(ask + W + "Script " + G + "> " + W)
       f = open(script, 'r')
       filedata = f.read()
       f.close()
       output = raw_input(ask + W + "Output " + G + "> " + W)
       f = open(output, 'w')
       f.write(output)
       f.close()
       os.system("bash-obfuscate " + script + " -o " + output )
       main (sukses + " Encrypt Successful...")
    except KeyboardInterrupt:
       print (eror + " Stopped!")
    except IOError:
       print (eror + " File Not Found!")
       os.system("sleep 3")
       enkrip()

def update():
    try:
       os.system("clear")
       print logo
       print
       main(sukses + " Checking version")
       os.system("sleep 2")
       print version
       os.system("sleep 3")
       print
       os.system("clear")
       print logo
       print
       main(sukses + " Please wait for check update version")
       os.system("sleep 3")
       main(dwn + " Connect to djunekz/baxter")
       os.system("sleep 3")
       os.system("clear")
       print logo
       print
       print (sukses + " New version availabel!")
       print
    except KeyboardInterrupt:
       print (eror + " Stopped!")
    def ya():
        try:
           os.system("clear")
           print logo
           print
           print (Y + " Choose your OS System" + W + " :")
           print cos
           def tmux():
               try:
                  os.system("clear")
                  print logo
                  print
                  main (dwn + " Processing to update new version, please don't close this session")
                  os.system("wget --quiet https://github.com/djunekz/baxter/releases/latest/download/baxter.tar.gz")
                  os.system("tar -xf baxter.tar.gz && rm baxter.tar.gz && mv baxter /data/data/com.termux/files/usr/bin && chmod +x /data/data/com.termux/files/usr/bin/baxter")
                  print (sukses + " Reading packages list... Done")
                  os.system("sleep 1")
                  print (sukses + " Building packages... Done")
                  os.system("sleep 1")
                  print (sukses + " Reading state information... Done")
                  os.system("sleep 1")
                  print (sukses + " Update successful!")
                  os.system("sleep 3")
                  os.system("baxter")
               except KeyboardInterrupt:
                  print (eror + " Stopped!")
           def linux():
               try:
                  os.system("clear")
                  print logo
                  print
                  main (dwn + " Processing to update new version, please don't close this session")
                  os.system("wget --quiet https://github.com/djunekz/baxter/releases/latest/download/baxter.tar.gz")
                  os.system("tar -xf baxter.tar.gz && sudo rm baxter.tar.gz && sudo mv baxter $HOME/../../usr/bin && chmod +x $HOME/../../usr/bin/baxter")
                  print (sukses + " Reading packages list... Done")
                  os.system("sleep 1")
                  print (sukses + " Building packages... Done")
                  os.system("sleep 1")
                  print (sukses + " Reading state information... Done")
                  os.system("sleep 1")
                  print (sukses + " Update successful!")
                  os.system("sleep 3")
                  os.system("baxter")
               except KeyboardInterrupt:
                  print (eror + " Stopped!")
           oss = raw_input(W + " Choose" + G + " > " + W)
           if oss == "1" or oss == "01":
               tmux()
           if oss == "2" or oss == "02":
               linux()
           else:
               print(eror + " Wrong Input!")
               os.system("sleep 1")
               print(eror + " Please choose 1 for termux, 2 for linux")
               os.system("sleep 3")
               ya()
        except KeyboardInterrupt:
           print (eror + " Stopped!")
    def no():
        try:
           os.system("clear")
           print logo
           print
           main (eror + " Don't need for update?")
           os.system("sleep 3")
           os.system("baxter")
        except KeyboardInterrupt:
           print (eror + "Stopped!")
    tanya = raw_input(W + " Do you need Update?" + Y + " [Y/n]" + G + " > " + W)
    if tanya == "Y" or tanya == "y":
        ya()
    if tanya == "N" or tanya == "n":
        no()
    else:
        print (eror + " Wrong Input!")
        os.system("sleep 3")
        update()

def cus():
    try:
       print
       main(G +" > " + W + "Who Am I ?" + Y + " = " + R + "Djunekz / Mr xXx / Hmei7 / MrDee / RedhH")
       print
       main(C + " Social media links and also email " + Y + " ("+ W +"UPDATED"+ Y +")")
       print
       main(sukses + " Instagram" + R + " : " + Y + "https://instagram.com/triple_x_redhh")
       main(sukses + " TikTok" + R + " : " + Y + "https://www.tiktok.com/@anonymous_id_")
       main(sukses + " Github" + R + " : " + Y + "https://github.com/djunekz")
       main(sukses + " Email" + R + " : ")
       print(G +" > " + W + " xxx.canon600@passinbox.com " + G + " ("+ Y +"Hmei7"+ G +")")
       print(G +" > " + W + " github.guiding533@passinbox.com " + G + " ("+ Y +"Djunekz"+ G +")")
       print(G +" > " + W + " mail.reconfirm867@passinbox.com " + G + " ("+ Y +"Mr xXx"+ G +")")
       print(G +" > " + W + " gab288.gab288@passinbox.com " + G + " ("+ Y +"RedHh"+ G +")")
       print(G +" > " + W + " www.handshake311@passinbox.com " + G + " ("+ Y +"MrDee"+ G +")")
       print
       print note
       print(tl + " ENGLISH")
       main(G + "   Emails are sent from the dark web, it is recommended to send messages only for short Q&A purposes, if you want to chat freely it is recommended to use social media.")
       print
       print(tl + " INDONESIA")
       main(G + "   Email dikirim dari dark web, disarankan untuk mengirim pesan hanya untuk keperluan tanya jawab singkat, jika ingin ngobrol bebas disarankan menggunakan media sosial.")
       print
       print note
       main (recode)
       os.system("sleep 2")
       takok()
    except KeyboardInterrupt:
       main(eror + " Wrong Input!")
       os.system("sleep 3")
       os.system("baxter")

def takok():
    takok = raw_input(W + "Choose" + G + " > " + W)
    if takok == "1" or takok == "01":
       enkrip()
    elif takok == "2" or takok == "02":
       dekrip()
    elif takok == "3" or takok == "03":
       cus()
    elif takok == "x" or takok == "X":
       os.system("exit")
    else:
       print (eror + " Wrong input")
       os.system("sleep 3")
       os.system("baxter")

try:
    takok()
except KeyboardInterrupt:
    print (eror + "Wrong Command!")
    sys.exit()
