#!/bin/bash
# Tool name : Installer BaxTER
# Information : Simple Encrypt and Decrypt files
# author : djunekz
# script note : free design jika ingin recode or copy script
# Jangan lupa cantumkan sumber/author name

clear
if [ -d /data/data/com.termux/files/usr/bin ]; then
  if [ ! -e /data/data/com.termux/files/usr/bin/ ];then
    pkg update
    pkg upgrade -y
    pkg install python python2
    pkg install nodejs
    pkg install nodejs-lts
    pkg install ruby -y
    npm -g install bash-obfuscate
  fi
fi
python2 baxter.py
exit
